name: Blackduck

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  BLACKDUCK_API_TOKEN:  ${{ secrets.BLACKDUCK_API_TOKEN }}
  BLACKDUCK_URL:  ${{ secrets.BLACKDUCK_URL }}
  DETECT_PROJECT_USER_GROUPS:  ${{ secrets.DETECT_PROJECT_USER_GROUPS }}
  DETECT_PROJECT_VERSION_DISTRIBUTION:  ${{ secrets.DETECT_PROJECT_VERSION_DISTRIBUTION }}

jobs:
  Scan:
    runs-on: ubuntu-latest
    name: Build job
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
          fetch-depth: 0
      - run: git fetch --all || echo "==> Accept any result"
      - name: set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Give permission
        shell: bash
        run: |
          chmod +x blackduck.sh
      - name: Run Blackduck scan
        shell: bash
        run: |
          ./blackduck.sh -d